import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import style from "../../styles/HomeStyle"
import Logo from "../../assets/images/logo.png"
import carsoulImage from "../../assets/images/Carsoule.png"
import FlashSale from '../../components/flashSale/FlashSale'
import PopularProducts from '../../components/popularProducts/PopularProducts'
import CategoriesSection from '../../components/categoriesSection/CategoriesSection'
import searchIcon from "../../assets/images/searchIcon.png"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fashion Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={style.header}>
          <div style={style.headerContainer}>

          <Image
          src={Logo}
          alt="logo"
          style={{width: 240, height: 80}}
          />
          <p style={style.headerText}>
            Category
          </p>
          <input style={style.searchField} type="text" placeholder='Search Your Fashion' />
          <button style={style.searchButton}>
            <Image
            src={searchIcon}
            alt="searchIcon"
            style={style.searchIcon}
            />
          </button>
          </div>
          <div style={style.headerText}>
            <h4>Home</h4>
            <h4>Our Stores</h4>
            <h4>About Us</h4>
            <h4>Login</h4>
            <h4>Signup</h4>
            <h4>Cart</h4>
          </div>
          
        </div>

        <div>
          <Image
          src={carsoulImage}
          alt="carsoul"
          style={{width: "100%", height: "auto"}}
          />

        </div>
        <div className="flashSale">
          <FlashSale />
        </div>
        <div className="popularProducts">
          <PopularProducts/>
        </div>
        <div className="categoriesSection">
          <CategoriesSection/>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
