import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import carsoulImage from "../../assets/images/Carsoule.png"
import FlashSale from '../../components/flashSale/FlashSale'
import PopularProducts from '../../components/popularProducts/PopularProducts'
import CategoriesSection from '../../components/categoriesSection/CategoriesSection'
import Header from '../../components/header/Header'
import Footer from '../../components/footer/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fashion Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header/>
        <div>
          <Image
          src={carsoulImage}
          alt="carsoul"
          style={{width: "100%", height: "auto"}}
          />

        </div>
        <div className="flashSale">
          <FlashSale />
        </div>
        <div className="popularProducts">
          <PopularProducts/>
        </div>
        <div className="categoriesSection">
          <CategoriesSection/>
        </div>
      </main>

      <footer className={styles.footer}>
        <Footer/>
      </footer>
    </div>
  )
}
